/**
 * Creating a sidebar enables you to:
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation

 * The id field is a unique ID for the sidebar.
 * The label field is the sidebar label. (optional)
 *
 * It is possible to have multiple sidebars for a single Docusaurus project.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // You can create a sidebar manually by specifying the docs's here.
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  // ],
};

module.exports = sidebars;